packages:
  - 'packages/client-core/core'
  - 'packages/client-apollo/apollo'
  - 'packages/client-react-query/react-query'
  - 'packages/client-relay/relay'
  - 'packages/client-urql/urql'
  - 'packages/cli'
  - 'packages/conformance'
  - 'packages/server-node'