/**
 * The reference schema as a TypeScript module, for packages that ship it.
 */

export const REFERENCE_MODULE_PATH = "packages/cli/src/lib/reference-schema.ts";

/**
 * @param {string} sdl the reference schema
 * @returns {string} the module source
 */
export function renderReferenceModule(sdl) {
  return `/**
 * The specification's reference schema, reference/cascade_base.graphql.
 * Generated by \`pnpm run sync:reference\`; do not edit.
 */
export const REFERENCE_SCHEMA: string = ${JSON.stringify(sdl)};
`;
}
